services:
  - type: web
    name: epub-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: REDIS_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true

  - type: worker
    name: epub-worker
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    startCommand: celery -A tasks worker --loglevel=info --concurrency=1
    envVars:
      - key: REDIS_URL
        sync: false
    autoDeploy: true
